package Hibernate.Clases;
// Generated 18-dic-2017 9:48:00 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Articulo generated by hbm2java
 */
@Entity
@Table(name="articulo"
    ,catalog="pruebas"
    , uniqueConstraints = @UniqueConstraint(columnNames="nombre") 
)
public class Articulo  implements java.io.Serializable {


     private Long id;
     private String nombre;
     private BigDecimal precio;
     private Long categoria;

    public Articulo() {
    }

	
    public Articulo(String nombre) {
        this.nombre = nombre;
    }
    public Articulo(String nombre, BigDecimal precio, Long categoria) {
       this.nombre = nombre;
       this.precio = precio;
       this.categoria = categoria;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    
    @Column(name="nombre", unique=true, nullable=false, length=50)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="precio", precision=10)
    public BigDecimal getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(BigDecimal precio) {
        this.precio = precio;
    }

    
    @Column(name="categoria")
    public Long getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Long categoria) {
        this.categoria = categoria;
    }




}


